### PR TITLE
terra-based reading/writing of netcdf files

### PR DESCRIPTION
**Pull request by pfuehrlich-pik**
The existing read/write support for netcdf based on ncdf4 and raster was not quite working as discussed [on mattermost](https://mattermost.pik-potsdam.de/landuse/pl/6xrxn7bccfyf3e6kg9rjutyu4o). With this PR nc files are written and read using terra.

The author of raster and terra recommends to not use the netcdf writing feature of raster, see [here](https://github.com/rspatial/terra/issues/94#issuecomment-736776956).

### CODE REVIEW

**Comment by mscrawford** [comment]
In testing this, I wrote a magclass object with 12 subdimensions until 2100. In a .mz format, this was around 36 mb. The write function worked, but produced a 227 mb sized .nc file (which I could interact with in Panoply fine, it seemed). However, this extremely large file breaks the readMagpieNC function (it hangs).

I can do some more tests when I have more time, but are .nc files usually 9x larger than their .mz equivalents? Even the uncompressed (.m) magpie file is only ~50 mb.

**Comment by pfuehrlich-pik** [comment]
@tscheypidi Please have a look, this may fix the CRAN windows problem. @dklein-pik had the same problem locally

**Review by dklein-pik — APPROVED** [review]
With these changes `test-readwritemagpie.R:87:3`, which previously failed on my Windows computer, works again.

**Review by tscheypidi — APPROVED** [review]
looks good, thanks!

**Pull request merged**
