### PR TITLE
added @export to maggply.R

### PR DESCRIPTION
**Pull request by bs538**
Added missing @export statement to magpply.R so that magpply() function can be used.

### CODE REVIEW

**Comment by tscheypidi** [comment]
You need to run lucode::buildLibrary() on the package first to increment the version number and to verify that your changes have been properly tested.

**Comment by bs538** [comment]
argh, forgot that, thanks for the reminder. did it now, runs fine, except for a warning about UTF-8 encoding (below). do I need to fix these or can I ignore them for now?

Warning messages:
1: roxygen2 requires Encoding: UTF-8 
2: roxygen2 requires Encoding: UTF-8

**Comment by tscheypidi** [comment]
Concerning the encoding: There was a line missing in the DESCRIPTION clarifying the used encoding. I just added it to your pull request.

**Comment by bs538** [comment]
Thanks! For future reference, is there a way to have the encoding written into DESCRIPTION automatically?

**Comment by tscheypidi** [comment]
This only has to be done once. Roxygen2 just recently switched its behavior demanding UTF-8 encoding. Before that there was no need to specify the encoding in the DESCRIPTION. Magclass was just not updated since this change....

**Pull request merged**
