### PR TITLE
Add magpie method for tibble::as_tibble()

### PR DESCRIPTION
**Pull request by johanneskoch94**
I would love to have this. I transform magpie objects to tibbles constantly, and this would make it super easy ;)
I have this PR as a draft, because a development version of roxygen is required. I suggest we wait until the next roxygen version is released before merging...

### CODE REVIEW

**Comment by tscheypidi** [comment]
looks good. Is it correct to assume that without this method applying `as_tibble` to a magclass object leads to an error? Because otherwise we would need to check whether `as_tibble` is perhaps already applied somewhere to a magclass object in our codebase.

**Comment by johanneskoch94** [comment]
Yes, the error that appears is: `Error in x@.Data[i, j, , drop = FALSE] : incorrect number of dimensions`

**Comment by johanneskoch94** [comment]
Hi @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q , I just learned about `quitte::magclass_to_tibble()` and wanted to tag you here, in case you had an opinion/suggestions.

**Comment by johanneskoch94** [comment]
Ready to merge! :)

**Review by tscheypidi — APPROVED** [review]
looks good

**Pull request merged**
